version: "3"
services:
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379
    networks: 
      - dev_network
  celery:
    build: .
    container_name: "celery"
    command: celery -A automoticz.celery.celery_app worker --loglevel=debug
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    links:
      - redis
    networks: 
      - dev_network
networks:
  dev_network:
    external: false

