default:
  PUBLIC_URL: http://192.168.0.108:5000
  LOGGING_SETTINGS: "{BASE_URL}/logging.ini"
  DEBUG: false

  ENCODING_FOR_DYNACONF: "utf-8"

  JWT_BLACKLIST_ENABLED: true
  JWT_REFRESH_TOKEN_EXPIRES: false
  JWT_ACCESS_TOKEN_EXPIRES: 300 # 5 minutes
  JWT_TOKEN_LOCATION: ["json", "headers"]

  SWAGGER_UI_JSONEDITOR: true

  CACHE_TYPE: "simple"
  CACHE_DEFAULT_TIMEOUT: 600

  SQLALCHEMY_TRACK_MODIFICATIONS: true

  CLIENT_SECRETS_FILE: "{BASE_URL}/data/client-secrets.json"
  CREDENTIALS_FILE: "{BASE_URL}/data/credentials.json"
  ENABLED_ENDPOINTS:
    - module: "automoticz.api.beacon_auth"
      url_path: "/beacon_auth"
    - module: "automoticz.api.system"
      url_path: "/system"
    - module: "automoticz.api.oauth2"
      url_path: "/oauth2"
  CELERY_TASKS:
    - "automoticz.tasks"
  RELOAD_PIN_ON_START: false
  SOKETIO_QUEUE: null
development:
  DEBUG: true
  SQLALCHEMY_DATABASE_URI: "sqlite:///{BASE_URL}/db.sqlite3"
  CELERY_BROKER_URL: "redis://localhost:6379/0"
  CELERY_RESULT_BACKEND: null
  CACHE_TYPE: "redis"
  CACHE_REDIS_HOST: 'localhost'
  CELERY_TASK_DEFAULT_QUEUE: "automoticz"
  SOKETIO_QUEUE: "redis://localhost:6379/0"
  RELOAD_PIN_ON_START: true
testing:
  DEBUG: true
  WT_ACCESS_TOKEN_EXPIRES: 10 # 5 minutes
  SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"
  CELERY_BROKER_URL: "redis://localhost:6379/0"
  CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
  CELERY_TASK_DEFAULT_QUEUE: "automoticz_test"
production:
  RELOAD_PIN_ON_START: false
  CELERY_TASK_DEFAULT_QUEUE: "automoticz"