class ENV:
    DEVELOPMENT = 'development'
    TESTING = 'testing'
    PRODUCTION = 'production'


class MESSAGE:
    LOGIN = 'LOGIN'
    REGISTER = 'REGISTER'
    REFRESH = 'REFRESH'
    REVOKE_ACCESS = 'REVOKE-ACCESS'
    REVOKE_REFRESH = 'REVOKE-REFRESH'
    API_NOT_INITIALIZED = 'API-NOT-INITIALIZED'
    NO_CREDENTIALS_PROVIDED = 'NO-CREDENTIALS-PROVIDED'
    INVALID_UTOKEN = 'INVALID-PIN'
    INVALID_CREDS = 'INVALID-CREDS'
    UKNOWN_LOGIN = 'UKNOWN-LOGIN'

PIN_ATTACHMENT_KEY = 'pin'
CACHE_PIN_KEY = 'pin'
CACHE_SET_PIN_KEY = 'set_pin'
CACHE_SET_PIN_KEY_TIMEOUT = 30
CACHE_LONG_TIMEOUT = 86400