"""empty message

Revision ID: b2ff51045fa2
Revises: 47118133633d
Create Date: 2019-06-30 18:00:26.693742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ff51045fa2'
down_revision = '47118133633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wsdevices', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wsdevices', 'description')
    # ### end Alembic commands ###
